{
    var demoDiv = document.getElementById("demoDiv");
    var divMessage = "Start Message";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Array Destructing ----------------------------------  <br> ";
    divMessage += "<b>Destructing</b> is the convenient way of <b>extracting data</b> stored in the <br>";
    divMessage += "<b>Object</b> & <b>Array</b> <br>";
    divMessage += "Whenever we require partial data from Array or Object in the LHS into the RHS<br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 1----------------------------------  <br> ";
    var input = [1, 2, 3, 4, 5, 6, 7, 8];
    var first_normal = input[0];
    var second_normal = input[1];
    var third_normal = input[2];
    divMessage += "    let input = [1, 2, 3,4,5,6,7,8]; <br>";
    divMessage += " let first_normal: number = input[0];  <br>";
    divMessage += " let second_normal: number = input[1]; <br>";
    divMessage += " let third_normal: number = input[2]; <br>";
    divMessage += "input data - first_normal: " + first_normal + " - second_normal :" + second_normal + " - third_normal:" + third_normal + " <br>";
    var first = input[0], second = input[1], third = input[2];
    divMessage += " let [first, second, third] = input; <br>";
    divMessage += "input data used via destructing - " + first + " - " + second + " - " + third + " <br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2 Using ...(Spread Operator) ----------------------------------  <br> ";
    var n1 = input[0], restdata = input.slice(1);
    divMessage += "  let [n1, ...restdata] = input; <br>";
    divMessage += "n1 :> " + n1 + ".   restdata ;> " + restdata + "<br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2-1 Using ...(Spread Operator) ----------------------------------  <br> ";
    var a1 = input[0], a2 = input[1], restdata1 = input.slice(2);
    divMessage += "  let [a1, a2, ...restdata1] = input; <br>";
    divMessage += "a1 :> " + a1 + ".   restdata ;> " + restdata1 + "<br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2-2 Using ...(Spread Operator) ----------------------------------  <br> ";
    var m1 = input[0];
    divMessage += "  let [m1] = input; <br>";
    divMessage += "m1 :> " + m1 + ".   Rest of the dat will be neglected..<br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2-3 Using ...(Spread Operator) ----------------------------------  <br> ";
    var m2 = input[2];
    divMessage += "  let [,,m2] = input;  <br>";
    divMessage += "m2 :> " + m2 + ".  (,) Comma will be neglected i.e. m2 = 3 Rest of the dat will be neglected..<br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2-4 Using ...(Spread Operator) ----------------------------------  <br> ";
    var m3 = input[2], m4 = input[3], m5 = input[5];
    divMessage += "   let [, , m3, m4 , ,m5 ] = input;  <br>";
    divMessage += "m3 :> " + m3 + ".  m4 :> " + m4 + ".  m5 :> " + m5 + ". (,) Comma will be neglected i.e. m3 = 3, m4 = 4  & m5 = 6 <br>";
    divMessage += " Rest of the dat will be neglected..<br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2-5 Using ...(Spread Operator) ----------------------------------  <br> ";
    var _a = /^(\d{4})-(\d{2})-(\d{2})$/.exec("1988-07-07") || ["No Data", "", "", ""], totalDate = _a[0], year = _a[1], month = _a[2], day = _a[3];
    divMessage += "  let [totalDate, year, month, day] = /^(\d{4})-(\d{2})-(\d{2})$/.exec('1988 - 07 - 07') || ['No Data','','','']; <br>";
    divMessage += " TotalDate :> " + totalDate + ". Year :> " + year + ". month :>" + month + ". day :> " + day + ". <br>";
    demoDiv.innerHTML = divMessage;
    divMessage += " <br> ---------------------------------- Example Type 2-6 Using ...(Spread Operator) ----------------------------------  <br> ";
    var _b = /^(\d{4})-(\d{2})-(\d{2})$/.exec("1988-7-07") || ["No Data", "", "", ""], totalDate1 = _b[0], year1 = _b[1], month1 = _b[2], day1 = _b[3];
    divMessage += "  let [totalDate, year, month, day] = /^(\d{4})-(\d{2})-(\d{2})$/.exec('1988 - 07 - 07') || ['No Data','','','']; <br>";
    divMessage += " totalDate1 :> " + totalDate1 + ". year1 :> " + year1 + ". month1 :>" + month1 + ". day1 :> " + day1 + ". <br>";
    divMessage += " No Date will be displayed as exec will not be able to process regex.<br>";
    demoDiv.innerHTML = divMessage;
}
//# sourceMappingURL=DS_Demo_1.js.map